---
# Source: glovo-backend-service/templates/hpa.yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache-hpa
  namespace: default
spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30  
  behavior:
     scaleDown:
       stabilizationWindowSeconds:  240
       policies:    
       - type: Percent
         value: 25
         periodSeconds: 60    
       - type: Pods
         value: 2
         periodSeconds: 90
     scaleUp:
       stabilizationWindowSeconds:  60
       policies:    
       - type: Percent
         value: 350
         periodSeconds: 30    
       - type: Pods
         value: 5
         periodSeconds: 30
